# This compose fragment describes development environment
# modifications to the original compose file.
version: "3"
services: 
  monopoly:
    env_file: 
      - ./env/local/local.env
      - ./env/local/secrets.env
    networks:
      - monopoly-net
    build:
      context: .
      dockerfile: ./env/Dockerfile
    ports:
      - "6363:6363"
      
networks:
  monopoly-net:
    external: false